# Generated by Django 5.1.3 on 2024-12-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('cuteness', models.CharField(max_length=50)),
                ('softness', models.CharField(max_length=50)),
            ],
        ),
    ]
